export const BAD_CREDENTIALS = 'BAD_CREDENTIALS';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const FORM_NOT_VALID = 'FORM_NOT_VALID';
export const NOT_IMPLEMENTED = 'NOT_IMPLEMENTED';
export const RECAPTCHA_ERROR = 'RECAPTCHA_ERROR';
